In [1]:
import pandas as pd

In [3]:
customers = pd.read_csv(r"C:\Users\LENOVO\Documents\DA-Test\customers.csv")

In [4]:
subscriptions = pd.read_csv(r"C:\Users\LENOVO\Documents\DA-Test\subscriptions.csv")

In [5]:
events = pd.read_csv(r"C:\Users\LENOVO\Documents\DA-Test\events.csv")

In [6]:
customers.head()

  customer_id signup_date     segment country  is_enterprise
0       C0001  2023-01-04  Enterprise      IN           True
1       C0002  2023-01-14         SMB      CA          False
2       C0003  2023-01-04         SMB      IN          False
3       C0004  2023-03-19         SMB      CA          False
4       C0005  2023-03-25         NaN      IN          False

In [7]:
subscriptions.head()

  subscription_id customer_id  start_date    end_date  monthly_price    status
0          S00001       C0001  10-01-2023         NaN            499    active
1          S00002       C0002  12-01-2023         NaN             49    active
2          S00003       C0003  08-01-2023  14-02-2023            149  canceled
3          S00004       C0004  21-01-2023         NaN            149    active
4          S00005       C0005  03-04-2023         NaN             99    active

In [8]:
events.head()

  event_id customer_id   event_type  event_date    source
0  E000001       C0001       signup  10-03-2023   organic
1  E000002       C0001       signup  10-03-2023   organic
2  E000003       C0002       signup  27-03-2023       ads
3  E000004       C0002  trial_start  28-03-2023       ads
4  E000005       C0003       signup  19-02-2023  referral

In [9]:
customers.isna().sum()

customer_id        0
signup_date       36
segment          243
country            0
is_enterprise      0
dtype: int64

In [10]:
subscriptions.duplicated().sum()

0

In [11]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2411 entries, 0 to 2410
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event_id     2411 non-null   object
 1   customer_id  2411 non-null   object
 2   event_type   2411 non-null   object
 3   event_date   2411 non-null   object
 4   source       2411 non-null   object
dtypes: object(5)
memory usage: 94.3+ KB

In [12]:
events['event_type'].value_counts()

event_type
signup         1094
trial_start     676
activated       404
churned         237
Name: count, dtype: int64

In [13]:
events['source'].value_counts()

source
outbound    643
organic     617
ads         614
referral    537
Name: count, dtype: int64

In [14]:
events.duplicated().sum()

0

In [16]:
customers.duplicated().sum()

0